//! Low-level input: `Input.dispatchMouseEvent`, `Input.dispatchKeyEvent`,
//! `Input.insertText`. Coordinates come from `DOM.getContentQuads` (works
//! without `DOM.enable`).
//!
//! Key names follow the DOM `KeyboardEvent.key` values (`Enter`, `Tab`,
//! `Escape`, `Backspace`, `ArrowLeft`, `F5`, `a`, `A`, `1`, `!`, …) with a
//! few aliases (`Esc`, `Return`, `Left`, `Space`). Combos join modifiers
//! with `+`: `Shift+Tab`, `Ctrl+a`, `Meta+Enter`, `Alt+ArrowLeft`;
//! `Mod` means `Meta` on macOS and `Ctrl` elsewhere. Each key carries the
//! `key`, `code`, `windowsVirtualKeyCode` and `text` Chrome expects from a
//! US keyboard.

use crate::error::BrowserError;
use surf_cdp::protocol::input;
use surf_cdp::Session;

/// Mouse button.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MouseButton {
    /// Left.
    Left,
    /// Right.
    Right,
    /// Middle.
    Middle,
}

impl MouseButton {
    /// CDP name.
    pub fn as_str(&self) -> &'static str {
        match self {
            MouseButton::Left => "left",
            MouseButton::Right => "right",
            MouseButton::Middle => "middle",
        }
    }

    fn cdp(&self) -> input::MouseButton {
        match self {
            MouseButton::Left => input::MouseButton::Left,
            MouseButton::Right => input::MouseButton::Right,
            MouseButton::Middle => input::MouseButton::Middle,
        }
    }

    /// The `buttons` bit-field value while this button is down.
    fn mask(&self) -> i64 {
        match self {
            MouseButton::Left => 1,
            MouseButton::Right => 2,
            MouseButton::Middle => 4,
        }
    }
}

/// Modifier bits as CDP wants them.
pub mod modifier {
    /// Alt / Option.
    pub const ALT: i64 = 1;
    /// Control.
    pub const CTRL: i64 = 2;
    /// Meta / Command / Windows.
    pub const META: i64 = 4;
    /// Shift.
    pub const SHIFT: i64 = 8;
}

/// One key as Chrome expects it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KeyDef {
    /// `KeyboardEvent.key`.
    pub key: String,
    /// `KeyboardEvent.code` (physical key).
    pub code: &'static str,
    /// `windowsVirtualKeyCode`.
    pub key_code: i64,
    /// Text generated by the key, if any (`keyDown` with `text` inserts
    /// it; without text the event is a `rawKeyDown`).
    pub text: Option<String>,
}

/// A parsed `Ctrl+Shift+a`-style combination.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct KeyPress {
    /// The non-modifier key.
    pub key: KeyDef,
    /// Modifier bit-field.
    pub modifiers: i64,
}

fn named(key: &str, code: &'static str, key_code: i64, text: Option<&str>) -> KeyDef {
    KeyDef {
        key: key.to_owned(),
        code,
        key_code,
        text: text.map(str::to_owned),
    }
}

/// Look up a key by name or single character. `None` for unknown names
/// and for characters outside the US layout (those go through
/// `Input.insertText` instead).
pub fn lookup(name: &str) -> Option<KeyDef> {
    let def = match name {
        "Enter" | "Return" => named("Enter", "Enter", 13, Some("\r")),
        "Tab" => named("Tab", "Tab", 9, None),
        "Escape" | "Esc" => named("Escape", "Escape", 27, None),
        "Backspace" => named("Backspace", "Backspace", 8, None),
        "Delete" | "Del" => named("Delete", "Delete", 46, None),
        "Insert" => named("Insert", "Insert", 45, None),
        "Space" => named(" ", "Space", 32, Some(" ")),
        "ArrowLeft" | "Left" => named("ArrowLeft", "ArrowLeft", 37, None),
        "ArrowUp" | "Up" => named("ArrowUp", "ArrowUp", 38, None),
        "ArrowRight" | "Right" => named("ArrowRight", "ArrowRight", 39, None),
        "ArrowDown" | "Down" => named("ArrowDown", "ArrowDown", 40, None),
        "Home" => named("Home", "Home", 36, None),
        "End" => named("End", "End", 35, None),
        "PageUp" => named("PageUp", "PageUp", 33, None),
        "PageDown" => named("PageDown", "PageDown", 34, None),
        "CapsLock" => named("CapsLock", "CapsLock", 20, None),
        "Shift" => named("Shift", "ShiftLeft", 16, None),
        "Control" | "Ctrl" => named("Control", "ControlLeft", 17, None),
        "Alt" | "Option" => named("Alt", "AltLeft", 18, None),
        "Meta" | "Cmd" | "Command" => named("Meta", "MetaLeft", 91, None),
        "F1" => named("F1", "F1", 112, None),
        "F2" => named("F2", "F2", 113, None),
        "F3" => named("F3", "F3", 114, None),
        "F4" => named("F4", "F4", 115, None),
        "F5" => named("F5", "F5", 116, None),
        "F6" => named("F6", "F6", 117, None),
        "F7" => named("F7", "F7", 118, None),
        "F8" => named("F8", "F8", 119, None),
        "F9" => named("F9", "F9", 120, None),
        "F10" => named("F10", "F10", 121, None),
        "F11" => named("F11", "F11", 122, None),
        "F12" => named("F12", "F12", 123, None),
        _ => {
            let mut chars = name.chars();
            let c = chars.next()?;
            if chars.next().is_some() {
                return None;
            }
            return char_key(c);
        }
    };
    Some(def)
}

/// A printable character on the US layout.
pub fn char_key(c: char) -> Option<KeyDef> {
    let (code, key_code): (&'static str, i64) = match c {
        'a' | 'A' => ("KeyA", 65),
        'b' | 'B' => ("KeyB", 66),
        'c' | 'C' => ("KeyC", 67),
        'd' | 'D' => ("KeyD", 68),
        'e' | 'E' => ("KeyE", 69),
        'f' | 'F' => ("KeyF", 70),
        'g' | 'G' => ("KeyG", 71),
        'h' | 'H' => ("KeyH", 72),
        'i' | 'I' => ("KeyI", 73),
        'j' | 'J' => ("KeyJ", 74),
        'k' | 'K' => ("KeyK", 75),
        'l' | 'L' => ("KeyL", 76),
        'm' | 'M' => ("KeyM", 77),
        'n' | 'N' => ("KeyN", 78),
        'o' | 'O' => ("KeyO", 79),
        'p' | 'P' => ("KeyP", 80),
        'q' | 'Q' => ("KeyQ", 81),
        'r' | 'R' => ("KeyR", 82),
        's' | 'S' => ("KeyS", 83),
        't' | 'T' => ("KeyT", 84),
        'u' | 'U' => ("KeyU", 85),
        'v' | 'V' => ("KeyV", 86),
        'w' | 'W' => ("KeyW", 87),
        'x' | 'X' => ("KeyX", 88),
        'y' | 'Y' => ("KeyY", 89),
        'z' | 'Z' => ("KeyZ", 90),
        '0' | ')' => ("Digit0", 48),
        '1' | '!' => ("Digit1", 49),
        '2' | '@' => ("Digit2", 50),
        '3' | '#' => ("Digit3", 51),
        '4' | '$' => ("Digit4", 52),
        '5' | '%' => ("Digit5", 53),
        '6' | '^' => ("Digit6", 54),
        '7' | '&' => ("Digit7", 55),
        '8' | '*' => ("Digit8", 56),
        '9' | '(' => ("Digit9", 57),
        ' ' => ("Space", 32),
        ';' | ':' => ("Semicolon", 186),
        '=' | '+' => ("Equal", 187),
        ',' | '<' => ("Comma", 188),
        '-' | '_' => ("Minus", 189),
        '.' | '>' => ("Period", 190),
        '/' | '?' => ("Slash", 191),
        '`' | '~' => ("Backquote", 192),
        '[' | '{' => ("BracketLeft", 219),
        '\\' | '|' => ("Backslash", 220),
        ']' | '}' => ("BracketRight", 221),
        '\'' | '"' => ("Quote", 222),
        '\n' | '\r' => return lookup("Enter"),
        '\t' => return lookup("Tab"),
        _ => return None,
    };
    Some(KeyDef {
        key: c.to_string(),
        code,
        key_code,
        text: Some(c.to_string()),
    })
}

/// Parse `Shift+Tab`, `Ctrl+a`, `Meta+Shift+z`, `Enter`, `+` (a lone plus
/// is the plus key).
pub fn parse_combo(spec: &str) -> Result<KeyPress, BrowserError> {
    let bad = |why: String| BrowserError::Config {
        what: "key".into(),
        reason: why,
    };
    let spec = spec.trim();
    if spec.is_empty() {
        return Err(bad("empty key".into()));
    }
    // A trailing `+` is the plus key itself (`+`, `Shift++`).
    let (mods, last) = match spec.strip_suffix('+') {
        Some(rest) => (rest.trim_end_matches('+'), "+"),
        None => match spec.rsplit_once('+') {
            Some((m, k)) => (m, k),
            None => ("", spec),
        },
    };
    let mut modifiers = 0;
    for m in mods.split('+').filter(|m| !m.is_empty()) {
        modifiers |= match m {
            "Shift" => modifier::SHIFT,
            "Control" | "Ctrl" => modifier::CTRL,
            "Alt" | "Option" => modifier::ALT,
            "Meta" | "Cmd" | "Command" | "Super" => modifier::META,
            "Mod" | "ControlOrMeta" => {
                if cfg!(target_os = "macos") {
                    modifier::META
                } else {
                    modifier::CTRL
                }
            }
            other => return Err(bad(format!("unknown modifier {other:?} in {spec:?}"))),
        };
    }
    let key = lookup(last).ok_or_else(|| bad(format!("unknown key {last:?} in {spec:?}")))?;
    Ok(KeyPress { key, modifiers })
}

/// Editing commands Chrome on macOS only performs when told explicitly
/// (`Input.dispatchKeyEvent.commands`); elsewhere the native shortcut
/// handling does it.
fn commands_for(press: &KeyPress) -> Option<Vec<String>> {
    if !cfg!(target_os = "macos") || press.modifiers & modifier::META == 0 {
        return None;
    }
    let shift = press.modifiers & modifier::SHIFT != 0;
    let cmd = match press.key.key.to_ascii_lowercase().as_str() {
        "a" => "SelectAll",
        "c" => "Copy",
        "x" => "Cut",
        "v" => "Paste",
        "z" if shift => "Redo",
        "z" => "Undo",
        _ => return None,
    };
    Some(vec![cmd.to_owned()])
}

/// `keyDown` (or `rawKeyDown` when the key produces no text) + `keyUp`.
///
/// Only `windowsVirtualKeyCode` is sent, never `nativeVirtualKeyCode`: on
/// macOS Chrome reads the native code as a Mac virtual key (65 = keypad
/// `.`), and `Ctrl+a` then showed up in the page as a storm of repeated
/// `.` keydowns with `ctrlKey` set.
pub async fn press_key(session: &Session, press: &KeyPress) -> Result<(), BrowserError> {
    let k = &press.key;
    // With Ctrl/Alt/Meta held the key does not insert its text.
    let inserts = press.modifiers & (modifier::CTRL | modifier::ALT | modifier::META) == 0;
    let text = if inserts { k.text.clone() } else { None };
    let kind = if text.is_some() {
        "keyDown"
    } else {
        "rawKeyDown"
    };
    session
        .send(input::DispatchKeyEvent {
            r#type: kind.into(),
            modifiers: Some(press.modifiers),
            text: text.clone(),
            unmodified_text: text,
            key: Some(k.key.clone()),
            code: Some(k.code.into()),
            windows_virtual_key_code: Some(k.key_code),
            commands: commands_for(press),
            ..Default::default()
        })
        .await?;
    session
        .send(input::DispatchKeyEvent {
            r#type: "keyUp".into(),
            modifiers: Some(press.modifiers),
            key: Some(k.key.clone()),
            code: Some(k.code.into()),
            windows_virtual_key_code: Some(k.key_code),
            ..Default::default()
        })
        .await?;
    Ok(())
}

/// `Input.insertText` (IME-style insertion; fires `input` events).
pub async fn insert_text(session: &Session, text: &str) -> Result<(), BrowserError> {
    session
        .send(input::InsertText {
            text: text.to_owned(),
        })
        .await?;
    Ok(())
}

/// `mouseMoved` to `(x, y)`.
pub async fn mouse_move(session: &Session, x: f64, y: f64) -> Result<(), BrowserError> {
    session
        .send(input::DispatchMouseEvent {
            r#type: "mouseMoved".into(),
            x,
            y,
            ..Default::default()
        })
        .await?;
    Ok(())
}

/// `mouseMoved` → `mousePressed` → `mouseReleased` at `(x, y)`,
/// `click_count` times (2 = double-click).
pub async fn click_at(
    session: &Session,
    x: f64,
    y: f64,
    button: MouseButton,
    click_count: i64,
) -> Result<(), BrowserError> {
    mouse_move(session, x, y).await?;
    for n in 1..=click_count.max(1) {
        session
            .send(input::DispatchMouseEvent {
                r#type: "mousePressed".into(),
                x,
                y,
                button: Some(button.cdp()),
                buttons: Some(button.mask()),
                click_count: Some(n),
                ..Default::default()
            })
            .await?;
        session
            .send(input::DispatchMouseEvent {
                r#type: "mouseReleased".into(),
                x,
                y,
                button: Some(button.cdp()),
                buttons: Some(0),
                click_count: Some(n),
                ..Default::default()
            })
            .await?;
    }
    Ok(())
}

/// `mouseWheel` at `(x, y)` by `(dx, dy)` CSS pixels.
pub async fn wheel(
    session: &Session,
    x: f64,
    y: f64,
    dx: f64,
    dy: f64,
) -> Result<(), BrowserError> {
    session
        .send(input::DispatchMouseEvent {
            r#type: "mouseWheel".into(),
            x,
            y,
            delta_x: Some(dx),
            delta_y: Some(dy),
            ..Default::default()
        })
        .await?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn named_keys_and_characters() {
        let enter = lookup("Enter").unwrap();
        assert_eq!(
            (enter.key.as_str(), enter.code, enter.key_code),
            ("Enter", "Enter", 13)
        );
        assert_eq!(enter.text.as_deref(), Some("\r"));
        assert!(lookup("Tab").unwrap().text.is_none());
        let a = lookup("a").unwrap();
        assert_eq!((a.key.as_str(), a.code, a.key_code), ("a", "KeyA", 65));
        let bang = lookup("!").unwrap();
        assert_eq!(
            (bang.key.as_str(), bang.code, bang.key_code),
            ("!", "Digit1", 49)
        );
        assert!(lookup("é").is_none());
        assert!(lookup("NoSuchKey").is_none());
    }

    #[test]
    fn combos() {
        let p = parse_combo("Ctrl+Shift+a").unwrap();
        assert_eq!(p.modifiers, modifier::CTRL | modifier::SHIFT);
        assert_eq!(p.key.key, "a");
        let p = parse_combo("Shift+Tab").unwrap();
        assert_eq!(p.modifiers, modifier::SHIFT);
        assert_eq!(p.key.code, "Tab");
        assert_eq!(parse_combo("+").unwrap().key.key, "+");
        assert_eq!(parse_combo("Shift++").unwrap().key.key, "+");
        assert!(parse_combo("Hyper+a").is_err());
        assert!(parse_combo("").is_err());
    }
}
