//! Protocol codegen (Decision 11).
//!
//! Reads `protocol/browser_protocol.json` + `protocol/js_protocol.json`
//! and writes `$OUT_DIR/protocol.rs` containing one `pub mod <domain>` per
//! allow-listed domain with:
//!
//! * named types → `pub type` aliases, `pub struct`s or `pub enum`s;
//! * commands → a `Serialize` params struct implementing `Command`
//!   (`const METHOD`, `type Response`) and a `Deserialize` response struct;
//! * events → a `Deserialize` params struct implementing `ProtocolEvent`.
//!
//! Deliberately simple: inline enums are `String`, `any`/opaque objects are
//! `serde_json::Value`, references to domains outside the allow-list are
//! `serde_json::Value`. Output order follows the JSON, so the file is
//! byte-for-byte deterministic. `Runtime.enable` and `DOM.enable` are not
//! generated at all (quiet rule 1/3).

use serde_json::Value;
use std::collections::{HashMap, HashSet};
use std::fmt::Write as _;
use std::path::PathBuf;

const ALLOW: &[&str] = &[
    "Target",
    "Page",
    "Runtime",
    "DOM",
    "Input",
    "Network",
    "Fetch",
    "Emulation",
    "Browser",
    "Storage",
    "IO",
    "Security",
];

/// `Domain.command` pairs that must never exist as typed commands.
const FORBIDDEN: &[(&str, &str)] = &[("Runtime", "enable"), ("DOM", "enable")];

/// Name of the `#[serde(other)]` variant added to every generated enum.
const CATCH_ALL: &str = "Unrecognized";

const RUST_KEYWORDS: &[&str] = &[
    "abstract", "as", "async", "await", "become", "box", "break", "const", "continue", "crate",
    "do", "dyn", "else", "enum", "extern", "false", "final", "fn", "for", "gen", "if", "impl",
    "in", "let", "loop", "macro", "match", "mod", "move", "mut", "override", "priv", "pub", "ref",
    "return", "self", "static", "struct", "super", "trait", "true", "try", "type", "typeof",
    "unsafe", "unsized", "use", "virtual", "where", "while", "yield",
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let proto_dir = manifest.join("../../protocol");
    let files = ["browser_protocol.json", "js_protocol.json"];
    println!("cargo:rerun-if-changed=build.rs");
    let mut domains: Vec<Value> = Vec::new();
    for f in files {
        let path = proto_dir.join(f);
        println!("cargo:rerun-if-changed={}", path.display());
        let text = std::fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        let v: Value = serde_json::from_str(&text).expect("protocol JSON");
        domains.extend(v["domains"].as_array().expect("domains").iter().cloned());
    }
    let selected: Vec<&Value> = ALLOW
        .iter()
        .map(|name| {
            domains
                .iter()
                .find(|d| d["domain"] == *name)
                .unwrap_or_else(|| panic!("domain {name} missing from protocol JSON"))
        })
        .collect();

    let index = TypeIndex::build(&selected);
    let mut out = String::new();
    writeln!(
        out,
        "// @generated by crates/surf-cdp/build.rs from protocol/*.json — do not edit."
    )
    .unwrap();
    for d in &selected {
        gen_domain(&mut out, d, &index);
    }
    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("protocol.rs");
    std::fs::write(&out_path, out).expect("write protocol.rs");
}

// ───────────────────────────── type index ─────────────────────────────

#[derive(Clone, Debug, PartialEq)]
enum Kind {
    /// Alias of a primitive / Vec / Value: `pub type X = …;`
    Alias(String),
    Enum,
    Struct,
}

struct TypeIndex {
    /// `"Domain.Type"` → kind.
    kinds: HashMap<String, Kind>,
    /// Struct → structs it contains *directly* (not through `Vec`).
    contains: HashMap<String, Vec<String>>,
}

impl TypeIndex {
    fn build(domains: &[&Value]) -> Self {
        let mut kinds = HashMap::new();
        let mut raw: Vec<(String, &Value)> = Vec::new();
        for d in domains {
            let dn = d["domain"].as_str().unwrap();
            for t in arr(&d["types"]) {
                let full = format!("{dn}.{}", t["id"].as_str().unwrap());
                let kind = match t["type"].as_str().unwrap() {
                    "string" if t.get("enum").is_some() => Kind::Enum,
                    "object" if t.get("properties").is_some() => Kind::Struct,
                    _ => Kind::Alias(String::new()), // filled below (needs refs)
                };
                kinds.insert(full.clone(), kind);
                raw.push((full, t));
            }
        }
        let mut idx = TypeIndex {
            kinds,
            contains: HashMap::new(),
        };
        // Aliases need the index to resolve `$ref` items.
        for (full, t) in &raw {
            if idx.kinds[full] == Kind::Alias(String::new()) {
                let dn = full.split('.').next().unwrap();
                let rust = idx.rust_type(dn, t);
                idx.kinds.insert(full.clone(), Kind::Alias(rust));
            }
        }
        for (full, t) in &raw {
            if idx.kinds[full] != Kind::Struct {
                continue;
            }
            let dn = full.split('.').next().unwrap();
            let mut direct = Vec::new();
            for p in arr(&t["properties"]) {
                if let Some(r) = p.get("$ref").and_then(Value::as_str) {
                    let target = qualify(dn, r);
                    if idx.kinds.get(&target) == Some(&Kind::Struct) {
                        direct.push(target);
                    }
                }
            }
            idx.contains.insert(full.clone(), direct);
        }
        idx
    }

    /// Does `from` reach `to` through direct (non-`Vec`) containment?
    fn reaches(&self, from: &str, to: &str) -> bool {
        let mut seen = HashSet::new();
        let mut stack = vec![from.to_owned()];
        while let Some(cur) = stack.pop() {
            if cur == to {
                return true;
            }
            if !seen.insert(cur.clone()) {
                continue;
            }
            if let Some(next) = self.contains.get(&cur) {
                stack.extend(next.iter().cloned());
            }
        }
        false
    }

    /// Rust path for a `$ref` seen from domain `dn`; `Value` when the
    /// target domain is outside the allow-list.
    fn ref_path(&self, dn: &str, r: &str) -> String {
        let full = qualify(dn, r);
        let (d, t) = full.split_once('.').unwrap();
        if !self.kinds.contains_key(&full) {
            return "serde_json::Value".to_owned();
        }
        if d == dn {
            t.to_owned()
        } else {
            format!("super::{}::{t}", mod_name(d))
        }
    }

    /// Rust type for a property / type node.
    fn rust_type(&self, dn: &str, node: &Value) -> String {
        if let Some(r) = node.get("$ref").and_then(Value::as_str) {
            return self.ref_path(dn, r);
        }
        match node["type"].as_str().unwrap_or("any") {
            "string" | "binary" => "String".to_owned(),
            "integer" => "i64".to_owned(),
            "number" => "f64".to_owned(),
            "boolean" => "bool".to_owned(),
            "array" => format!("Vec<{}>", self.rust_type(dn, &node["items"])),
            _ => "serde_json::Value".to_owned(), // any, object without properties
        }
    }

    /// Field type inside struct `owner`: boxes direct self-reaching refs.
    fn field_type(&self, dn: &str, owner: Option<&str>, node: &Value) -> String {
        let base = self.rust_type(dn, node);
        if let (Some(owner), Some(r)) = (owner, node.get("$ref").and_then(Value::as_str)) {
            let target = qualify(dn, r);
            if self.kinds.get(&target) == Some(&Kind::Struct) && self.reaches(&target, owner) {
                return format!("Box<{base}>");
            }
        }
        base
    }

    /// Can `Default` be derived for a field of this node's type?
    fn is_defaultable(&self, dn: &str, node: &Value) -> bool {
        if node["optional"].as_bool().unwrap_or(false) {
            return true;
        }
        if let Some(r) = node.get("$ref").and_then(Value::as_str) {
            let full = qualify(dn, r);
            return match self.kinds.get(&full) {
                None => true, // serde_json::Value
                Some(Kind::Alias(_)) => true,
                Some(Kind::Enum) | Some(Kind::Struct) => false,
            };
        }
        true // primitives, arrays, any
    }
}

fn qualify(dn: &str, r: &str) -> String {
    if r.contains('.') {
        r.to_owned()
    } else {
        format!("{dn}.{r}")
    }
}

fn arr(v: &Value) -> &[Value] {
    v.as_array().map(Vec::as_slice).unwrap_or(&[])
}

// ───────────────────────────── emitters ─────────────────────────────

fn gen_domain(out: &mut String, d: &Value, idx: &TypeIndex) {
    let dn = d["domain"].as_str().unwrap();
    writeln!(out).unwrap();
    doc(out, "", d.get("description"), d);
    writeln!(out, "#[allow(missing_docs, clippy::all)]").unwrap();
    writeln!(out, "pub mod {} {{", mod_name(dn)).unwrap();
    writeln!(out, "    #[allow(unused_imports)]").unwrap();
    writeln!(out, "    use serde::{{Deserialize, Serialize}};").unwrap();
    writeln!(out, "    #[allow(unused_imports)]").unwrap();
    writeln!(
        out,
        "    use crate::protocol::{{Command, Empty, ProtocolEvent}};"
    )
    .unwrap();

    for t in arr(&d["types"]) {
        gen_type(out, dn, t, idx);
    }
    for c in arr(&d["commands"]) {
        let name = c["name"].as_str().unwrap();
        if FORBIDDEN.contains(&(dn, name)) {
            continue;
        }
        gen_command(out, dn, c, idx);
    }
    for e in arr(&d["events"]) {
        gen_event(out, dn, e, idx);
    }
    writeln!(out, "}}").unwrap();
}

fn gen_type(out: &mut String, dn: &str, t: &Value, idx: &TypeIndex) {
    let id = t["id"].as_str().unwrap();
    let full = format!("{dn}.{id}");
    writeln!(out).unwrap();
    doc(out, "    ", t.get("description"), t);
    match &idx.kinds[&full] {
        Kind::Alias(rust) => {
            writeln!(out, "    pub type {id} = {rust};").unwrap();
        }
        Kind::Enum => {
            writeln!(
                out,
                "    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]"
            )
            .unwrap();
            writeln!(out, "    pub enum {id} {{").unwrap();
            // serde matches the catch-all variant's *name* literally too, so
            // it must not equal any real value (`Unknown` and `Other` do).
            let mut used = HashSet::from([CATCH_ALL.to_owned()]);
            for v in arr(&t["enum"]) {
                let raw = v.as_str().unwrap();
                assert_ne!(
                    raw, CATCH_ALL,
                    "{full}: value collides with catch-all variant"
                );
                let mut variant = pascal(raw);
                if variant == "Self" {
                    variant.push('_');
                }
                let mut n = 2;
                let base = variant.clone();
                while !used.insert(variant.clone()) {
                    variant = format!("{base}{n}");
                    n += 1;
                }
                writeln!(out, "        /// `{raw}`").unwrap();
                writeln!(out, "        #[serde(rename = \"{raw}\")]").unwrap();
                writeln!(out, "        {variant},").unwrap();
            }
            writeln!(
                out,
                "        /// A value this build does not know (newer Chrome)."
            )
            .unwrap();
            writeln!(out, "        #[serde(other)]").unwrap();
            writeln!(out, "        {CATCH_ALL},").unwrap();
            writeln!(out, "    }}").unwrap();
        }
        Kind::Struct => {
            gen_struct(
                out,
                dn,
                id,
                Some(&full),
                arr(&t["properties"]),
                idx,
                Derives::Both,
            );
        }
    }
}

#[derive(Clone, Copy, PartialEq)]
enum Derives {
    Both,
    SerializeOnly,
    DeserializeOnly,
}

fn gen_struct(
    out: &mut String,
    dn: &str,
    name: &str,
    owner: Option<&str>,
    props: &[Value],
    idx: &TypeIndex,
    derives: Derives,
) {
    let defaultable = props.iter().all(|p| idx.is_defaultable(dn, p));
    let mut list = vec!["Debug", "Clone", "PartialEq"];
    if defaultable {
        list.push("Default");
    }
    match derives {
        Derives::Both => list.extend(["Serialize", "Deserialize"]),
        Derives::SerializeOnly => list.push("Serialize"),
        Derives::DeserializeOnly => list.push("Deserialize"),
    }
    writeln!(out, "    #[derive({})]", list.join(", ")).unwrap();
    writeln!(out, "    pub struct {name} {{").unwrap();
    for p in props {
        let orig = p["name"].as_str().unwrap();
        let (ident, plain) = field_ident(orig);
        let optional = p["optional"].as_bool().unwrap_or(false);
        let ty = idx.field_type(dn, owner, p);
        doc(out, "        ", p.get("description"), p);
        if plain != orig {
            writeln!(out, "        #[serde(rename = \"{orig}\")]").unwrap();
        }
        if optional {
            if derives != Derives::DeserializeOnly {
                writeln!(
                    out,
                    "        #[serde(skip_serializing_if = \"Option::is_none\")]"
                )
                .unwrap();
            }
            if derives != Derives::SerializeOnly {
                writeln!(out, "        #[serde(default)]").unwrap();
            }
            writeln!(out, "        pub {ident}: Option<{ty}>,").unwrap();
        } else {
            writeln!(out, "        pub {ident}: {ty},").unwrap();
        }
    }
    writeln!(out, "    }}").unwrap();
}

fn gen_command(out: &mut String, dn: &str, c: &Value, idx: &TypeIndex) {
    let name = c["name"].as_str().unwrap();
    let pname = pascal(name);
    let method = format!("{dn}.{name}");
    writeln!(out).unwrap();
    doc(
        out,
        "    ",
        Some(&Value::String(format!("`{method}`"))),
        &Value::Null,
    );
    doc(out, "    ", c.get("description"), c);
    gen_struct(
        out,
        dn,
        &pname,
        None,
        arr(&c["parameters"]),
        idx,
        Derives::SerializeOnly,
    );
    let returns = arr(&c["returns"]);
    let response = if returns.is_empty() {
        "Empty".to_owned()
    } else {
        let rname = format!("{pname}Response");
        writeln!(out).unwrap();
        writeln!(out, "    /// Result of `{method}`.").unwrap();
        gen_struct(
            out,
            dn,
            &rname,
            None,
            returns,
            idx,
            Derives::DeserializeOnly,
        );
        rname
    };
    writeln!(out).unwrap();
    writeln!(out, "    impl Command for {pname} {{").unwrap();
    writeln!(out, "        const METHOD: &'static str = \"{method}\";").unwrap();
    writeln!(out, "        type Response = {response};").unwrap();
    writeln!(out, "    }}").unwrap();
}

fn gen_event(out: &mut String, dn: &str, e: &Value, idx: &TypeIndex) {
    let name = e["name"].as_str().unwrap();
    let sname = format!("{}Event", pascal(name));
    let method = format!("{dn}.{name}");
    writeln!(out).unwrap();
    doc(
        out,
        "    ",
        Some(&Value::String(format!("`{method}`"))),
        &Value::Null,
    );
    doc(out, "    ", e.get("description"), e);
    gen_struct(
        out,
        dn,
        &sname,
        None,
        arr(&e["parameters"]),
        idx,
        Derives::DeserializeOnly,
    );
    writeln!(out, "    impl ProtocolEvent for {sname} {{").unwrap();
    writeln!(out, "        const METHOD: &'static str = \"{method}\";").unwrap();
    writeln!(out, "    }}").unwrap();
}

/// Emit `/// …` lines: description plus experimental/deprecated markers.
fn doc(out: &mut String, indent: &str, description: Option<&Value>, node: &Value) {
    if let Some(text) = description.and_then(Value::as_str) {
        for line in text.lines() {
            let line = line.trim_end();
            if line.is_empty() {
                writeln!(out, "{indent}///").unwrap();
            } else {
                writeln!(out, "{indent}/// {}", line.replace("*/", "* /")).unwrap();
            }
        }
    }
    let experimental = node["experimental"].as_bool().unwrap_or(false);
    let deprecated = node["deprecated"].as_bool().unwrap_or(false);
    if experimental || deprecated {
        let mut tags = Vec::new();
        if experimental {
            tags.push("experimental");
        }
        if deprecated {
            tags.push("deprecated");
        }
        writeln!(out, "{indent}///").unwrap();
        writeln!(out, "{indent}/// ({})", tags.join(", ")).unwrap();
    }
}

// ───────────────────────────── naming ─────────────────────────────

fn mod_name(domain: &str) -> String {
    snake(domain)
}

/// Split an identifier into words at `-`, `_`, spaces and camel-case
/// boundaries (`consoleAPICalled` → `console`, `API`, `Called`).
fn words(s: &str) -> Vec<String> {
    let chars: Vec<char> = s.chars().collect();
    let mut words = Vec::new();
    let mut cur = String::new();
    for (i, &c) in chars.iter().enumerate() {
        if !c.is_alphanumeric() {
            if !cur.is_empty() {
                words.push(std::mem::take(&mut cur));
            }
            continue;
        }
        let prev = if i > 0 { Some(chars[i - 1]) } else { None };
        let next = chars.get(i + 1).copied();
        let boundary = match prev {
            Some(p) if p.is_alphanumeric() => {
                (c.is_uppercase() && (p.is_lowercase() || p.is_ascii_digit()))
                    || (c.is_uppercase()
                        && p.is_uppercase()
                        && next.map(|n| n.is_lowercase()).unwrap_or(false))
            }
            _ => false,
        };
        if boundary && !cur.is_empty() {
            words.push(std::mem::take(&mut cur));
        }
        cur.push(c);
    }
    if !cur.is_empty() {
        words.push(cur);
    }
    words
}

fn pascal(s: &str) -> String {
    let mut out = String::new();
    for w in words(s) {
        let mut it = w.chars();
        if let Some(first) = it.next() {
            out.extend(first.to_uppercase());
            out.extend(it.flat_map(char::to_lowercase));
        }
    }
    if out
        .chars()
        .next()
        .map(|c| c.is_ascii_digit())
        .unwrap_or(true)
    {
        out.insert(0, 'N');
    }
    out
}

fn snake(s: &str) -> String {
    words(s)
        .iter()
        .map(|w| w.to_lowercase())
        .collect::<Vec<_>>()
        .join("_")
}

/// `(identifier as written in code, identifier without `r#`)`.
fn field_ident(orig: &str) -> (String, String) {
    let plain = snake(orig);
    if matches!(plain.as_str(), "self" | "super" | "crate") {
        let ident = format!("{plain}_");
        (ident.clone(), ident)
    } else if RUST_KEYWORDS.contains(&plain.as_str()) {
        (format!("r#{plain}"), plain)
    } else {
        (plain.clone(), plain)
    }
}
